### ISSUE TITLE
Предлагаю некоторые исправления

### ISSUE THREAD

**Issue by Yurajun** [agragregra/YDNjQ-Snippets#1]
`function isWindow(obj) {
  return obj !== null && obj !== undefined && obj === obj.window;
}

// Native
function isPlainObject(obj) {
  if (typeof (obj) !== 'object' || obj.nodeType || obj !== null && obj !== undefined && obj === obj.window) {
    return false;
  }

  if (obj.constructor &&
      !Object.prototype.hasOwnProperty.call(obj.constructor.prototype, 'isPrototypeOf')) {
    return false;
  }

  return true;
}`

Заменить строки obj !== undefined на typeof obj !== 'undefined'
https://eslint.org/docs/rules/no-undefined

Сократить запись в snippet "siblings"
// Native - latest, Edge13+
`[...el.parentNode.children].filter((child) =>
  child !== el
);`
// Native (alternative) - latest, Edge13+
`Array.from(el.parentNode.children).filter((child) =>
  child !== el
);`
// Native - IE10+
`Array.prototype.filter.call(el.parentNode.children, (child) =>
  child !== el
);`
на
// Native - latest, Edge13+
`[...el.parentNode.children].filter(child => child !== el);`
// Native (alternative) - latest, Edge13+
`Array.from(el.parentNode.children).filter(child => child !== el);`
// Native - IE10+
`Array.prototype.filter.call(el.parentNode.children, child => child !== el);`

В snippet "contains" добавить es6 реализацию
`const contains = (selector, text) => 
  [...document.querySelectorAll(selector)].filter(el => el.textContent.includes(text))

`

**Comment by agragregra** [comment]
Здравствуйте. Благодарю.
Отправьте ваше предложение сюда https://github.com/nefe/You-Dont-Need-jQuery
Именно с оригинального репозитория был взят код и именно обновления этого репозитория будет влиять на обновления в сниппетах.
